### ISSUE TITLE
Distorted rendering results

### ISSUE THREAD

**Issue by tetsu-kikuchi** [limacv/GaussianSplattingViewer#14]
Hello, thank you for creating a valuable repo.  

When I viewed my ply file, the rendering results sometimes get distorted, as shown in the attached image. 

![screen_shot_2024-03-29_195155](https://github.com/limacv/GaussianSplattingViewer/assets/63581217/20c8eed7-3e87-436c-8acf-0215ebb0286b)

Could you give me any hints to solve this problem?   
This ply file was made by the original implementation of 3D Gaussian Splatting by graphdeco-inria.  I have checked that this ply is viewed normally in other viewers.

I am using Windows 10.  What I did is simply 
- git clone the repo,
- pip install -r requirements.txt (in conda environment with Python 3.11.8)
- python main.py
- load a ply file by the "open ply" button.

The following is the result of "pip list":

```
Package           Version
----------------- -------
asttokens         2.4.0
backcall          0.2.0
colorama          0.4.6
comm              0.1.4
debugpy           1.8.0
decorator         5.1.1
executing         1.2.0
glfw              2.7.0
imageio           2.34.0
imgui             2.0.0
ipykernel         6.25.2
ipython           8.15.0
jedi              0.19.0
jupyter_client    8.3.1
jupyter_core      5.3.1
matplotlib-inline 0.1.6
nest-asyncio      1.5.8
numpy             1.26.4
packaging         23.1
parso             0.8.3
pickleshare       0.7.5
pillow            10.2.0
pip               23.3.1
platformdirs      3.10.0
plyfile           1.0.3
prompt-toolkit    3.0.39
psutil            5.9.5
pure-eval         0.2.2
PyGLM             2.7.1
Pygments          2.16.1
PyOpenGL          3.1.7
python-dateutil   2.8.2
pywin32           306
pyzmq             25.1.1
setuptools        68.2.2
six               1.16.0
stack-data        0.6.2
tornado           6.3.3
wcwidth           0.2.6
wheel             0.41.2
```

**Comment by limacv** [comment]
What's actually what it looks like with wrong sorting (from front to back)! You didn't turn on the `auto sort`, which means that the order of Gaussians being rendered is always the same as when you clicked `sort Gaussians` button (or when you loaded the ply if you've never clicked the button). To render a Gaussian correctly, one need to sort the Gaussians every frame. So this is a desired behavior. 
To always get a correct order, turn on `auto sort`, or use cuda backend

**Comment by tetsu-kikuchi** [comment]
Thank you very much.  As you answered, the problem is resolved when I turned on "auto sort", and the rendering now works correctly.
