### ISSUE TITLE
Question about fisheye implementation

### ISSUE THREAD

**Issue by yudai-kato-aisin** [limacv/GaussianSplattingViewer#21]
I would like to ask a question about fisheye branch. I'm very interested in the fisheye projection for 3DGS.

Can I ask what fisheye model do you use? 
I have checked the Jacobian, but could not estimate the model due to lack of mathmatical knowledge.
 https://github.com/limacv/GaussianSplattingViewer/blob/647c0d415dcb58c636c237241fa7bf2a1b358e54/shaders/gau_vert.glsl#L107-L111

It's very helpful if you could answer my question.
Thank you in advance.

**Comment by limacv** [comment]
I'm using equidistant projection as in https://wiki.panotools.org/Fisheye_Projection

**Comment by yudai-kato-aisin** [comment]
Thank you very much for answering!
