### ISSUE TITLE
Missing a module?

### ISSUE THREAD

**Issue by bgpantojar** [limacv/GaussianSplattingViewer#4]
Dear all,

Nice repo.

I wanted to use it but it seems that there is a folder missing. Check the screenshot of my terminal.

![Screenshot from 2023-12-01 13-37-48](https://github.com/limacv/GaussianSplattingViewer/assets/35929939/127f6bcf-d5d2-4a94-ae6a-45501a880dda)

Thanks!

**Comment by ultra-sonic** [comment]
`pip install plyfile` and your good to go
